[package]
name = "blufio-telegram"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false
description = "Telegram channel adapter for Blufio"

[dependencies]
blufio-core = { path = "../blufio-core" }
blufio-config = { path = "../blufio-config" }
teloxide = { version = "0.17", features = ["macros"] }
reqwest.workspace = true
serde.workspace = true
serde_json = "1"
async-trait.workspace = true
semver.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros"] }
tracing.workspace = true
futures = "0.3"
base64 = "0.22"
chrono = "0.4"
tokio-util = { version = "0.7", features = ["rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
