[package]
name = "blufio-vault"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false
description = "AES-256-GCM encrypted credential vault for the Blufio agent framework"

[dependencies]
blufio-core = { path = "../blufio-core" }
blufio-config = { path = "../blufio-config" }
ring.workspace = true
argon2.workspace = true
secrecy.workspace = true
zeroize.workspace = true
rand.workspace = true
rpassword.workspace = true
tokio-rusqlite.workspace = true
rusqlite.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde_json = "1"
toml.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tempfile = "3"
blufio-storage = { path = "../blufio-storage" }
serial_test.workspace = true
