[package]
name = "blufio-router"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
blufio-config = { path = "../blufio-config" }
tracing.workspace = true

[dev-dependencies]
